language: php

php:
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master
    - dev
    - /^\d+\.\d+$/

before_install:
  - composer self-update

install: composer update $COMPOSER_FLAGS --prefer-dist

script: vendor/bin/phpunit -c phpunit.xml --debug --coverage-text